### ISSUE TITLE
Server Fuzzing Tutorial doc has invalid param name

### ISSUE THREAD

**Issue by samjeba** [cisco-sas/kitty#63]
Getting following error stack with pre_test param as "test_num"

[ERROR   ][base.start] Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kitty\fuzzers\base.py", line 292, in start
    self._test_environment()
  File "C:\Python27\lib\site-packages\kitty\fuzzers\server.py", line 53, in _test_environment
    if self._run_sequence(sequence):
  File "C:\Python27\lib\site-packages\kitty\fuzzers\server.py", line 64, in _run_sequence
    self._pre_test()
  File "C:\Python27\lib\site-packages\kitty\fuzzers\base.py", line 332, in _pre_test
    self.target.pre_test(self.model.current_index())
  File "F:\play\pyplay\fuzz1\fuzz1.py", line 42, in pre_test
    super(TcpTarget, self).pre_test(test_num)
  File "C:\Python27\lib\site-packages\kitty\targets\server.py", line 62, in pre_test
    super(ServerTarget, self).pre_test(test_num)
  File "C:\Python27\lib\site-packages\kitty\targets\base.py", line 81, in pre_test
    self.controller.pre_test(test_number=self.test_number)
TypeError: pre_test() got an unexpected keyword argument 'test_number'

doc link : http://kitty.readthedocs.io/en/latest/tutorials/server_fuzzing.html

**Comment by dark-lbp** [comment]
Can you post you test code?  This may help to reproduce the problem.

**Comment by BinyaminSharet** [comment]
This issue is now fixed on the next branch, will be pushed to master (and updated in readthedocs) in the next release.
