### ISSUE TITLE
Wrong pip package kittyfuzzer

### ISSUE THREAD

**Issue by GH0st3rs** [cisco-sas/kitty#69]
## My actions
```bash
1. docker run -it ubuntu:latest
2. apt update && apt upgrade -y && apt install -y python3-pip git
3. git clone https://github.com/cisco-sas/katnip.git /tmp/katnip
4. cd /tmp/katnip
5. pip3 install -e .
```
## Result
```bash
Obtaining file:///tmp/katnip
Collecting kittyfuzzer (from katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/61/fc/9b7b03d896d986aafb0000a093a0c9b599d26ba3b35d29e2ed0313b6d852/kittyfuzzer-0.7.1.tar.gz (301kB)
    100% |################################| 307kB 765kB/s 
  Running setup.py (path:/tmp/pip-build-g0ao1gtv/kittyfuzzer/setup.py) egg_info for package kittyfuzzer produced metadata for project name kittyfuzzer-remote. Fix your #egg=kittyfuzzer fragments.
Collecting docopt (from kittyfuzzer-remote->katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting requests (from kittyfuzzer-remote->katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |################################| 61kB 1.3MB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from kittyfuzzer-remote->katnip==0.2.5)
Collecting chardet<3.1.0,>=3.0.2 (from requests->kittyfuzzer-remote->katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 1.2MB/s 
Collecting certifi>=2017.4.17 (from requests->kittyfuzzer-remote->katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |################################| 163kB 447kB/s 
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests->kittyfuzzer-remote->katnip==0.2.5)
Collecting urllib3<1.25,>=1.21.1 (from requests->kittyfuzzer-remote->katnip==0.2.5)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |################################| 122kB 2.6MB/s 
Building wheels for collected packages: kittyfuzzer-remote, kittyfuzzer-remote, docopt
  Running setup.py bdist_wheel for kittyfuzzer-remote ... done
  Stored in directory: /root/.cache/pip/wheels/b0/fc/a8/c7bc608bd3245cd6da33cf9086be799297428057d765f88825
  Running setup.py bdist_wheel for kittyfuzzer-remote ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g0ao1gtv/kittyfuzzer-remote/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpugm93id4pip-wheel- --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-g0ao1gtv/kittyfuzzer-remote/setup.py'
  
  ----------------------------------------
  Failed building wheel for kittyfuzzer-remote
  Running setup.py clean for kittyfuzzer-remote
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g0ao1gtv/kittyfuzzer-remote/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-g0ao1gtv/kittyfuzzer-remote/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for kittyfuzzer-remote
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built kittyfuzzer-remote docopt
Failed to build kittyfuzzer-remote
Installing collected packages: docopt, chardet, certifi, urllib3, requests, kittyfuzzer-remote, katnip
  Running setup.py develop for katnip
Successfully installed certifi-2018.11.29 chardet-3.0.4 docopt-0.6.2 katnip kittyfuzzer-remote-0.7.1 requests-2.21.0 urllib
```

**Comment by BinyaminSharet** [comment]
kitty requires python2. the python3 module for kitty is only for the remote part of kitty (kittyfuzzer-remote).
katnip does not support python3 at all.
Please verify that the installation works for you on python2.

**Comment by GH0st3rs** [comment]
Ok, it working for python2. But why you don't want support python3?

**Comment by BinyaminSharet** [comment]
We have considered adding python3 support, but it requires quite an effort. You are welcome to do that yourself and submit a PR though :)
