### ISSUE TITLE
In Python3 no module cPickle

### ISSUE THREAD

**Issue by GH0st3rs** [cisco-sas/kitty#70]
https://github.com/cisco-sas/kitty/blob/f19e81124c08d926fdba533ed58ddbc4a941bdf5/kitty/data/data_manager.py#L23

```bash
root@bdeebb3c8e86:/tmp# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kitty.fuzzers import ServerFuzzer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/kitty/kitty/fuzzers/__init__.py", line 34, in <module>
    from kitty.fuzzers.base import BaseFuzzer
  File "/tmp/kitty/kitty/fuzzers/base.py", line 32, in <module>
    from kitty.data.data_manager import DataManager, SessionInfo
  File "/tmp/kitty/kitty/data/data_manager.py", line 23, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

[import _pickle as cPickle](https://askubuntu.com/questions/742782/how-to-install-cpickle-on-python-3-4)

**Comment by BinyaminSharet** [comment]
See my comments on issue #69
