### ISSUE TITLE
WebInterface. Address already in use

### ISSUE THREAD

**Issue by GH0st3rs** [cisco-sas/kitty#79]
If I try run fuzzing in loop, then after 1 loop iteration, WebInterface cant stopped, and continue bind the port. Why it's not stopped?
```python
for item in range(10):
            target = TcpTarget('fuzzer', host, int(port), timeout=1)
            target.set_expect_response(True)
            target.add_monitor(monitor)
            # Define model
            model = GraphModel()
            model.connect(template)
            # Define fuzzer
            fuzzer = ServerFuzzer()
            fuzzer.set_session_file('%s.sqlite' % time.ctime().replace(' ', '_'))
            fuzzer.set_interface(WebInterface(port=4445))
            fuzzer.set_model(model)
            fuzzer.set_target(target)
            fuzzer.set_delay_between_tests(0.2)
            fuzzer.start()
````

```[INFO    ][base._load_session] No session loaded
       _load_session No session loaded
[INFO    ][base._start_message] 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 127.0.0.1:4445
                 Log: ./kittylogs/kitty_20190213-175952.log

                 Total possible mutation count: 1316
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
      _start_message 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 127.0.0.1:4445
                 Log: ./kittylogs/kitty_20190213-175952.log

                 Total possible mutation count: 1316
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/media/DATA/Fuzzer/kitty3/kitty/core/threading_utils.py", line 42, in run
    self._func(*self._args)
  File "/media/DATA/Fuzzer/kitty3/kitty/interfaces/web.py", line 301, in _server_func
    server = _WebInterfaceServer((self._host, self._port), _WebInterfaceHandler, self)
  File "/media/DATA/Fuzzer/kitty3/kitty/interfaces/web.py", line 46, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by BinyaminSharet** [comment]
1. I don't see that you use `item` in your for loop, so you don't really need to do a loop, you can call it only once.
2. Regarding your actual problem - start() returns when there are no more mutations to send, however, in order to allow you to explore the results, it does not shut down the fuzzer components, WebInterface included. what you need to do is call `fuzzer.stop()` after `fuzzer.start()` (see the [examples](https://github.com/cisco-sas/kitty/blob/master/examples/01_file_generator/runner.py))
