### ISSUE TITLE
AttributeError: module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by silverfox983** [cisco-sas/kitty#92]
I'm getting this in python2 and python3 what's happening here.
when looking at the select module I see 
```
class poll():
    def __init__(self) -> None: ...
    def register(self, fd: _FileDescriptor, eventmask: int = ...) -> None: ...
    def modify(self, fd: _FileDescriptor, eventmask: int) -> None: ...
    def unregister(self, fd: _FileDescriptor) -> None: ...
    def poll(self, timeout: Optional[float] = ...) -> List[Tuple[int, int]]: ...

def select(rlist: Sequence[Any], wlist: Sequence[Any], xlist: Sequence[Any],
           timeout: Optional[float] = ...) -> Tuple[List[Any],
                                                    List[Any],
                                                    List[Any]]: ...

if sys.version_info >= (3, 3):
    error = OSError
else:
    class error(Exception): ...
```
**but when i run my script it gives me**
```
[ERROR   ][base.start] Error occurred while fuzzing: AttributeError("module 'select' has no attribute 'poll'")
[ERROR   ][base.start] Traceback (most recent call last):
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\kitty\fuzzers\base.py", line 385, in start
    self._test_environment()
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\kitty\fuzzers\server.py", line 53, in _test_environment
    if self._run_sequence(sequence):
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\kitty\fuzzers\server.py", line 75, in _run_sequence
    return self._post_test()
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\kitty\fuzzers\base.py", line 434, in _post_test
    self.target.post_test(self.model.current_index())
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\katnip\targets\application.py", line 131, in post_test
    self.report.add('stdout', self._read(self._process.stdout))
  File "C:\Users\silve\AppData\Local\Programs\Python\Python38\lib\site-packages\katnip\targets\application.py", line 121, in _read
    poll_obj = select.poll()
```

**Comment by BinyaminSharet** [comment]
Sorry for the delay, haven't been around for a long time.
This isn't an issue, the application.py module in [katnip](https://github.com/cisco-sas/katnip/blob/master/katnip/targets/application.py) doesn't support windows, only linux/MacOS
